// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/cart/cart.proto

package go_micro_service_cart

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CartInfo struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId            int64    `protobuf:"varint,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	SizeId               int64    `protobuf:"varint,4,opt,name=size_id,json=sizeId,proto3" json:"size_id,omitempty"`
	Num                  int64    `protobuf:"varint,5,opt,name=num,proto3" json:"num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CartInfo) Reset()         { *m = CartInfo{} }
func (m *CartInfo) String() string { return proto.CompactTextString(m) }
func (*CartInfo) ProtoMessage()    {}
func (*CartInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d07a9611505055b, []int{0}
}

func (m *CartInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CartInfo.Unmarshal(m, b)
}
func (m *CartInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CartInfo.Marshal(b, m, deterministic)
}
func (m *CartInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CartInfo.Merge(m, src)
}
func (m *CartInfo) XXX_Size() int {
	return xxx_messageInfo_CartInfo.Size(m)
}
func (m *CartInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CartInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CartInfo proto.InternalMessageInfo

func (m *CartInfo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CartInfo) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CartInfo) GetProductId() int64 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

func (m *CartInfo) GetSizeId() int64 {
	if m != nil {
		return m.SizeId
	}
	return 0
}

func (m *CartInfo) GetNum() int64 {
	if m != nil {
		return m.Num
	}
	return 0
}

type RespAddCart struct {
	CartId               int64    `protobuf:"varint,1,opt,name=cart_id,json=cartId,proto3" json:"cart_id,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespAddCart) Reset()         { *m = RespAddCart{} }
func (m *RespAddCart) String() string { return proto.CompactTextString(m) }
func (*RespAddCart) ProtoMessage()    {}
func (*RespAddCart) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d07a9611505055b, []int{1}
}

func (m *RespAddCart) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespAddCart.Unmarshal(m, b)
}
func (m *RespAddCart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespAddCart.Marshal(b, m, deterministic)
}
func (m *RespAddCart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespAddCart.Merge(m, src)
}
func (m *RespAddCart) XXX_Size() int {
	return xxx_messageInfo_RespAddCart.Size(m)
}
func (m *RespAddCart) XXX_DiscardUnknown() {
	xxx_messageInfo_RespAddCart.DiscardUnknown(m)
}

var xxx_messageInfo_RespAddCart proto.InternalMessageInfo

func (m *RespAddCart) GetCartId() int64 {
	if m != nil {
		return m.CartId
	}
	return 0
}

func (m *RespAddCart) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type ReqClean struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqClean) Reset()         { *m = ReqClean{} }
func (m *ReqClean) String() string { return proto.CompactTextString(m) }
func (*ReqClean) ProtoMessage()    {}
func (*ReqClean) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d07a9611505055b, []int{2}
}

func (m *ReqClean) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqClean.Unmarshal(m, b)
}
func (m *ReqClean) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqClean.Marshal(b, m, deterministic)
}
func (m *ReqClean) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqClean.Merge(m, src)
}
func (m *ReqClean) XXX_Size() int {
	return xxx_messageInfo_ReqClean.Size(m)
}
func (m *ReqClean) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqClean.DiscardUnknown(m)
}

var xxx_messageInfo_ReqClean proto.InternalMessageInfo

func (m *ReqClean) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type Resp struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Resp) Reset()         { *m = Resp{} }
func (m *Resp) String() string { return proto.CompactTextString(m) }
func (*Resp) ProtoMessage()    {}
func (*Resp) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d07a9611505055b, []int{3}
}

func (m *Resp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resp.Unmarshal(m, b)
}
func (m *Resp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resp.Marshal(b, m, deterministic)
}
func (m *Resp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resp.Merge(m, src)
}
func (m *Resp) XXX_Size() int {
	return xxx_messageInfo_Resp.Size(m)
}
func (m *Resp) XXX_DiscardUnknown() {
	xxx_messageInfo_Resp.DiscardUnknown(m)
}

var xxx_messageInfo_Resp proto.InternalMessageInfo

func (m *Resp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type ReqIncr struct {
	CartId               int64    `protobuf:"varint,1,opt,name=cart_id,json=cartId,proto3" json:"cart_id,omitempty"`
	ChangeNum            int64    `protobuf:"varint,2,opt,name=change_num,json=changeNum,proto3" json:"change_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqIncr) Reset()         { *m = ReqIncr{} }
func (m *ReqIncr) String() string { return proto.CompactTextString(m) }
func (*ReqIncr) ProtoMessage()    {}
func (*ReqIncr) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d07a9611505055b, []int{4}
}

func (m *ReqIncr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqIncr.Unmarshal(m, b)
}
func (m *ReqIncr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqIncr.Marshal(b, m, deterministic)
}
func (m *ReqIncr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqIncr.Merge(m, src)
}
func (m *ReqIncr) XXX_Size() int {
	return xxx_messageInfo_ReqIncr.Size(m)
}
func (m *ReqIncr) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqIncr.DiscardUnknown(m)
}

var xxx_messageInfo_ReqIncr proto.InternalMessageInfo

func (m *ReqIncr) GetCartId() int64 {
	if m != nil {
		return m.CartId
	}
	return 0
}

func (m *ReqIncr) GetChangeNum() int64 {
	if m != nil {
		return m.ChangeNum
	}
	return 0
}

type ReqDecr struct {
	CartId               int64    `protobuf:"varint,1,opt,name=cart_id,json=cartId,proto3" json:"cart_id,omitempty"`
	ChangeNum            int64    `protobuf:"varint,2,opt,name=change_num,json=changeNum,proto3" json:"change_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqDecr) Reset()         { *m = ReqDecr{} }
func (m *ReqDecr) String() string { return proto.CompactTextString(m) }
func (*ReqDecr) ProtoMessage()    {}
func (*ReqDecr) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d07a9611505055b, []int{5}
}

func (m *ReqDecr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqDecr.Unmarshal(m, b)
}
func (m *ReqDecr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqDecr.Marshal(b, m, deterministic)
}
func (m *ReqDecr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqDecr.Merge(m, src)
}
func (m *ReqDecr) XXX_Size() int {
	return xxx_messageInfo_ReqDecr.Size(m)
}
func (m *ReqDecr) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqDecr.DiscardUnknown(m)
}

var xxx_messageInfo_ReqDecr proto.InternalMessageInfo

func (m *ReqDecr) GetCartId() int64 {
	if m != nil {
		return m.CartId
	}
	return 0
}

func (m *ReqDecr) GetChangeNum() int64 {
	if m != nil {
		return m.ChangeNum
	}
	return 0
}

type ReqCartId struct {
	CartId               int64    `protobuf:"varint,1,opt,name=cart_id,json=cartId,proto3" json:"cart_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqCartId) Reset()         { *m = ReqCartId{} }
func (m *ReqCartId) String() string { return proto.CompactTextString(m) }
func (*ReqCartId) ProtoMessage()    {}
func (*ReqCartId) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d07a9611505055b, []int{6}
}

func (m *ReqCartId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqCartId.Unmarshal(m, b)
}
func (m *ReqCartId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqCartId.Marshal(b, m, deterministic)
}
func (m *ReqCartId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqCartId.Merge(m, src)
}
func (m *ReqCartId) XXX_Size() int {
	return xxx_messageInfo_ReqCartId.Size(m)
}
func (m *ReqCartId) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqCartId.DiscardUnknown(m)
}

var xxx_messageInfo_ReqCartId proto.InternalMessageInfo

func (m *ReqCartId) GetCartId() int64 {
	if m != nil {
		return m.CartId
	}
	return 0
}

type ReqGetAll struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqGetAll) Reset()         { *m = ReqGetAll{} }
func (m *ReqGetAll) String() string { return proto.CompactTextString(m) }
func (*ReqGetAll) ProtoMessage()    {}
func (*ReqGetAll) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d07a9611505055b, []int{7}
}

func (m *ReqGetAll) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqGetAll.Unmarshal(m, b)
}
func (m *ReqGetAll) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqGetAll.Marshal(b, m, deterministic)
}
func (m *ReqGetAll) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqGetAll.Merge(m, src)
}
func (m *ReqGetAll) XXX_Size() int {
	return xxx_messageInfo_ReqGetAll.Size(m)
}
func (m *ReqGetAll) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqGetAll.DiscardUnknown(m)
}

var xxx_messageInfo_ReqGetAll proto.InternalMessageInfo

func (m *ReqGetAll) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type RespGetAll struct {
	CartInfo             []*CartInfo `protobuf:"bytes,1,rep,name=cart_info,json=cartInfo,proto3" json:"cart_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *RespGetAll) Reset()         { *m = RespGetAll{} }
func (m *RespGetAll) String() string { return proto.CompactTextString(m) }
func (*RespGetAll) ProtoMessage()    {}
func (*RespGetAll) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d07a9611505055b, []int{8}
}

func (m *RespGetAll) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespGetAll.Unmarshal(m, b)
}
func (m *RespGetAll) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespGetAll.Marshal(b, m, deterministic)
}
func (m *RespGetAll) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespGetAll.Merge(m, src)
}
func (m *RespGetAll) XXX_Size() int {
	return xxx_messageInfo_RespGetAll.Size(m)
}
func (m *RespGetAll) XXX_DiscardUnknown() {
	xxx_messageInfo_RespGetAll.DiscardUnknown(m)
}

var xxx_messageInfo_RespGetAll proto.InternalMessageInfo

func (m *RespGetAll) GetCartInfo() []*CartInfo {
	if m != nil {
		return m.CartInfo
	}
	return nil
}

func init() {
	proto.RegisterType((*CartInfo)(nil), "go.micro.service.cart.CartInfo")
	proto.RegisterType((*RespAddCart)(nil), "go.micro.service.cart.RespAddCart")
	proto.RegisterType((*ReqClean)(nil), "go.micro.service.cart.ReqClean")
	proto.RegisterType((*Resp)(nil), "go.micro.service.cart.Resp")
	proto.RegisterType((*ReqIncr)(nil), "go.micro.service.cart.ReqIncr")
	proto.RegisterType((*ReqDecr)(nil), "go.micro.service.cart.ReqDecr")
	proto.RegisterType((*ReqCartId)(nil), "go.micro.service.cart.ReqCartId")
	proto.RegisterType((*ReqGetAll)(nil), "go.micro.service.cart.ReqGetAll")
	proto.RegisterType((*RespGetAll)(nil), "go.micro.service.cart.RespGetAll")
}

func init() { proto.RegisterFile("proto/cart/cart.proto", fileDescriptor_5d07a9611505055b) }

var fileDescriptor_5d07a9611505055b = []byte{
	// 408 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x94, 0xdf, 0x6a, 0xa3, 0x40,
	0x14, 0xc6, 0x63, 0xcc, 0x1a, 0x3d, 0x81, 0xb0, 0x0c, 0x84, 0x95, 0x2c, 0xd9, 0xcd, 0xce, 0xf6,
	0x22, 0x57, 0x16, 0xd2, 0x9b, 0x5e, 0xf4, 0x26, 0x4d, 0xa0, 0xd8, 0x42, 0xff, 0xf8, 0x02, 0xc1,
	0x3a, 0x93, 0x54, 0xf0, 0x4f, 0x32, 0x6a, 0xa1, 0x85, 0x3e, 0x6b, 0x5f, 0xa5, 0x9c, 0x19, 0x6d,
	0x73, 0x51, 0xb5, 0xd0, 0x9b, 0x30, 0x73, 0xce, 0x77, 0x7e, 0xf9, 0x8e, 0x9f, 0x08, 0xa3, 0x9d,
	0x48, 0xf3, 0xf4, 0x38, 0xf0, 0x45, 0x2e, 0x7f, 0x1c, 0x79, 0x27, 0xa3, 0x6d, 0xea, 0xc4, 0x61,
	0x20, 0x52, 0x27, 0xe3, 0xe2, 0x31, 0x0c, 0xb8, 0x83, 0x4d, 0xfa, 0x02, 0xe6, 0xd2, 0x17, 0xb9,
	0x9b, 0x6c, 0x52, 0x32, 0x84, 0x6e, 0xc8, 0x6c, 0x6d, 0xaa, 0xcd, 0x74, 0xaf, 0x1b, 0x32, 0xf2,
	0x0b, 0xfa, 0x45, 0xc6, 0xc5, 0x3a, 0x64, 0x76, 0x57, 0x16, 0x0d, 0xbc, 0xba, 0x8c, 0x4c, 0x00,
	0x76, 0x22, 0x65, 0x45, 0x90, 0x63, 0x4f, 0x97, 0x3d, 0xab, 0xac, 0xb8, 0x72, 0x2e, 0x0b, 0x9f,
	0x39, 0xf6, 0x7a, 0x6a, 0x0e, 0xaf, 0x2e, 0x23, 0x3f, 0x41, 0x4f, 0x8a, 0xd8, 0xfe, 0x21, 0x8b,
	0x78, 0xa4, 0xa7, 0x30, 0xf0, 0x78, 0xb6, 0x5b, 0x30, 0x86, 0x2e, 0x70, 0x12, 0x5d, 0xad, 0xdf,
	0x6d, 0x18, 0x78, 0x55, 0x93, 0x71, 0xb6, 0x95, 0x36, 0x2c, 0x0f, 0x8f, 0xf4, 0x3f, 0x98, 0x1e,
	0xdf, 0x2f, 0x23, 0xee, 0x27, 0x87, 0x46, 0xb5, 0x43, 0xa3, 0xd4, 0x86, 0x1e, 0xe2, 0xab, 0x71,
	0xed, 0x63, 0x7c, 0x01, 0x7d, 0x8f, 0xef, 0xdd, 0x24, 0x10, 0xf5, 0x7f, 0x3a, 0x01, 0x08, 0x1e,
	0xfc, 0x64, 0xcb, 0xd7, 0xe8, 0x5a, 0x3d, 0x02, 0x4b, 0x55, 0xae, 0x8b, 0xb8, 0x44, 0xac, 0xf8,
	0x37, 0x10, 0x47, 0x60, 0xe1, 0x12, 0x4a, 0x5b, 0x07, 0x29, 0x55, 0x17, 0x3c, 0x5f, 0x44, 0x51,
	0xfd, 0xae, 0x97, 0x00, 0xb8, 0x6b, 0x29, 0x3b, 0x03, 0x4b, 0xc1, 0x92, 0x4d, 0x6a, 0x6b, 0x53,
	0x7d, 0x36, 0x98, 0xff, 0x75, 0x3e, 0x7d, 0x05, 0x9c, 0x2a, 0x7f, 0xcf, 0x0c, 0xca, 0xd3, 0xfc,
	0x55, 0x87, 0x9e, 0x0c, 0xe4, 0x16, 0xfa, 0x55, 0x36, 0x6d, 0xe3, 0x63, 0x5a, 0x23, 0x38, 0x08,
	0x98, 0x76, 0xc8, 0x15, 0x58, 0x32, 0xb4, 0x46, 0x66, 0x95, 0xec, 0xf8, 0x77, 0x03, 0x93, 0x76,
	0x88, 0x0b, 0x26, 0x46, 0x28, 0x59, 0x7f, 0xea, 0x59, 0xa8, 0xf9, 0x02, 0x0a, 0xa3, 0x6c, 0x43,
	0xa1, 0xa6, 0x0d, 0x75, 0x07, 0xc3, 0x15, 0x8f, 0x78, 0xce, 0x11, 0x76, 0xfe, 0xe4, 0x32, 0x32,
	0x6d, 0xd8, 0x53, 0x66, 0xdc, 0x86, 0xbc, 0x01, 0xa3, 0x0c, 0xb6, 0x01, 0xa5, 0x14, 0xe3, 0x7f,
	0x0d, 0x28, 0x25, 0xa1, 0x9d, 0x7b, 0x43, 0x7e, 0x15, 0x4e, 0xde, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x0f, 0xf2, 0x4d, 0x8e, 0x2e, 0x04, 0x00, 0x00,
}
