version: '3.1'

services:
  civil:
    build: ./
    image: shrot:1.0
    container_name: changz
    restart: always
    environment:
      MYSQL_DSN: "root:root@tcp/mall_db?charset=utf8&parseTime=True&loc=Local"
    ports:
      - 9020:9020
    depends_on:
      - mysql
  mysql:
    container_name: mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mall_db
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    ports:
      - 3306:3306
